### ISSUE TITLE
Proposal 1: Initial Policy

### ISSUE THREAD

**Issue by gdude2002** [FabriCommunity/fabricommunity.github.io#4]
This is the discussion issue for our first policy proposal. It's the first version of our policies, and getting it right is important - so I'd like to get as much feedback from everyone as possible!

If you don't have a GitHub account, you can always chat in `#discord-meta` as well.

You can find the proposal [on the site](https://fabricmc.community/community/proposals/initial-policy/).

**Comment by Leo40Git** [comment]
`We do not currently have a way to appeal community bans.`

An extremely simple (read: not troll-proofed in the slightest) method to doing this would be creating an appeal form using Google Forms and manually processing the responses. This should probably be used as a stopgap until we can figure out a proper system for it.
